import { useEffect } from "react"
import { usePreferences } from "@/queries/preferences"

export const LANGUAGES = [
  { value: "en", label: "English", dir: "ltr" },
  { value: "hi", label: "हिन्दी (Hindi)", dir: "ltr" },
  { value: "es", label: "Español", dir: "ltr" },
  { value: "fr", label: "Français", dir: "ltr" },
  { value: "de", label: "Deutsch", dir: "ltr" },
  { value: "ar", label: "العربية (Arabic)", dir: "rtl" },
] as const

export type Language = (typeof LANGUAGES)[number]["value"]
const english = {
  Settings: "Settings",
  General: "General",
  Appearance: "Appearance",
  Inbox: "Inbox",
  Composing: "Composing",
  Downloads: "Downloads",
  Identities: "Identities",
  "Vacation responder": "Vacation responder",
  Filters: "Filters",
  Templates: "Templates",
  Folders: "Folders",
  Tags: "Tags",
  "Content & senders": "Content & senders",
  Security: "Security",
  Features: "Features",
  Shortcuts: "Shortcuts",
  Account: "Account",
  Notifications: "Notifications",
  "Email, calendar and background alerts":
    "Email, calendar and background alerts",
  Mail: "Mail",
  Calendar: "Calendar",
  Contacts: "Contacts",
  Files: "Files",
  Workspace: "Workspace",
  "Privacy & Security": "Privacy & Security",
  "Back to workspace": "Back to workspace",
  Language: "Language",
  Timezone: "Timezone",
  "Default app": "Default app",
  "Display density": "Display density",
  "Used across the workspace interface.":
    "Used across the workspace interface.",
  "Used for dates and times across mail and calendar.":
    "Used for dates and times across mail and calendar.",
  "The app you land in. Changing it switches you there now.":
    "The app you land in. Changing it switches you there now.",
  "Overall spacing of the interface.": "Overall spacing of the interface.",
  "Automatic (device)": "Automatic (device)",
  Comfortable: "Comfortable",
  Compact: "Compact",
  Compose: "Compose",
  Mailboxes: "Mailboxes",
  Starred: "Starred",
  Important: "Important",
  Sent: "Sent",
  Drafts: "Drafts",
  Archive: "Archive",
  Junk: "Junk",
  Trash: "Trash",
  Views: "Views",
  Month: "Month",
  Week: "Week",
  Day: "Day",
  Agenda: "Agenda",
  "Address books": "Address books",
  "Search mail": "Search mail",
  "Search results": "Search results",
  "Search trash…": "Search trash…",
  "Search mail (try: from:X, has:attachment)":
    "Search mail (try: from:X, has:attachment)",
  "Language, timezone and workspace defaults":
    "Language, timezone and workspace defaults",
  "Theme, type, scale, and color vision":
    "Theme, type, scale, and color vision",
  "Reading pane, density and previews": "Reading pane, density and previews",
  "Identity, signature and reply defaults":
    "Identity, signature and reply defaults",
  "Email and attachment file names": "Email and attachment file names",
  "Addresses available for sending": "Addresses available for sending",
  "Automatic out-of-office replies": "Automatic out-of-office replies",
  "Incoming mail rules": "Incoming mail rules",
  "Reusable email drafts": "Reusable email drafts",
  "Manage mailboxes": "Manage mailboxes",
  "Organize mail with labels": "Organize mail with labels",
  "Images and trusted senders": "Images and trusted senders",
  "Connection and session safety": "Connection and session safety",
  "Turn optional capabilities on or off":
    "Turn optional capabilities on or off",
  "Keyboard shortcut reference": "Keyboard shortcut reference",
  "Profile and session": "Profile and session",
  "Toggle sidebar": "Toggle sidebar",
  "Choose mailbox": "Choose mailbox",
  "Advanced mail search": "Advanced mail search",
  Back: "Back",
  "New folder": "New folder",
  "Folder name": "Folder name",
  "New folder name": "New folder name",
  "Select a conversation to read it.": "Select a conversation to read it.",
  "No messages matched your search.": "No messages matched your search.",
  "This mailbox is empty.": "This mailbox is empty.",
  "Load more messages": "Load more messages",
  "Loading more messages…": "Loading more messages…",
}
type Key = keyof typeof english
export type TranslationKey = Key

const translations = {
  en: english,
  hi: {
    Settings: "सेटिंग्स",
    General: "सामान्य",
    Appearance: "दिखावट",
    Inbox: "इनबॉक्स",
    Composing: "संदेश लिखना",
    Downloads: "डाउनलोड",
    Identities: "पहचान",
    "Vacation responder": "अवकाश उत्तर",
    Filters: "फ़िल्टर",
    Templates: "टेम्पलेट",
    Folders: "फ़ोल्डर",
    Tags: "टैग",
    "Content & senders": "सामग्री और प्रेषक",
    Security: "सुरक्षा",
    Features: "सुविधाएँ",
    Shortcuts: "शॉर्टकट",
    Account: "खाता",
    Mail: "मेल",
    Calendar: "कैलेंडर",
    Contacts: "संपर्क",
    Files: "फ़ाइलें",
    Workspace: "कार्यस्थान",
    "Privacy & Security": "गोपनीयता और सुरक्षा",
    "Back to workspace": "कार्यस्थान पर लौटें",
    Language: "भाषा",
    Timezone: "समय क्षेत्र",
    "Default app": "डिफ़ॉल्ट ऐप",
    "Display density": "प्रदर्शन घनत्व",
    "Used across the workspace interface.":
      "पूरे कार्यस्थान में उपयोग की जाती है।",
    "Used for dates and times across mail and calendar.":
      "मेल और कैलेंडर में तारीख और समय के लिए उपयोग होता है।",
    "The app you land in. Changing it switches you there now.":
      "शुरुआत में खुलने वाला ऐप। इसे बदलते ही ऐप बदल जाएगा।",
    "Overall spacing of the interface.": "इंटरफ़ेस में जगह का आकार।",
    "Automatic (device)": "स्वचालित (डिवाइस)",
    Comfortable: "आरामदायक",
    Compact: "सघन",
    Compose: "लिखें",
    Mailboxes: "मेलबॉक्स",
    Starred: "तारांकित",
    Important: "महत्वपूर्ण",
    Sent: "भेजे गए",
    Drafts: "ड्राफ़्ट",
    Archive: "संग्रह",
    Junk: "जंक",
    Trash: "कचरा",
    Views: "दृश्य",
    Month: "महीना",
    Week: "सप्ताह",
    Day: "दिन",
    Agenda: "कार्यसूची",
    "Address books": "पता पुस्तिकाएँ",
    "Search mail": "मेल खोजें",
    "Search results": "खोज परिणाम",
    "Search trash…": "कचरे में खोजें…",
    "Search mail (try: from:X, has:attachment)":
      "मेल खोजें (जैसे: from:X, has:attachment)",
    "Language, timezone and workspace defaults":
      "भाषा, समय क्षेत्र और कार्यस्थान की प्राथमिकताएँ",
    "Theme, type, scale, and color vision": "थीम, अक्षर, आकार और रंग",
    "Reading pane, density and previews": "पठन पैनल, घनत्व और पूर्वावलोकन",
    "Identity, signature and reply defaults":
      "पहचान, हस्ताक्षर और उत्तर विकल्प",
    "Email and attachment file names": "ईमेल और अटैचमेंट के नाम",
    "Addresses available for sending": "भेजने के लिए उपलब्ध पते",
    "Automatic out-of-office replies": "स्वचालित अनुपस्थिति उत्तर",
    "Incoming mail rules": "आने वाली मेल के नियम",
    "Reusable email drafts": "पुन: उपयोग योग्य ईमेल ड्राफ़्ट",
    "Manage mailboxes": "मेलबॉक्स प्रबंधित करें",
    "Organize mail with labels": "लेबल से मेल व्यवस्थित करें",
    "Images and trusted senders": "चित्र और विश्वसनीय प्रेषक",
    "Connection and session safety": "कनेक्शन और सत्र सुरक्षा",
    "Turn optional capabilities on or off":
      "वैकल्पिक सुविधाएँ चालू या बंद करें",
    "Keyboard shortcut reference": "कीबोर्ड शॉर्टकट",
    "Profile and session": "प्रोफ़ाइल और सत्र",
    "Toggle sidebar": "साइडबार बदलें",
    "Choose mailbox": "मेलबॉक्स चुनें",
    "Advanced mail search": "उन्नत मेल खोज",
    Back: "वापस",
  },
  es: {
    Settings: "Configuración",
    General: "General",
    Appearance: "Apariencia",
    Inbox: "Recibidos",
    Composing: "Redacción",
    Downloads: "Descargas",
    Identities: "Identidades",
    "Vacation responder": "Respuesta automática",
    Filters: "Filtros",
    Templates: "Plantillas",
    Folders: "Carpetas",
    Tags: "Etiquetas",
    "Content & senders": "Contenido y remitentes",
    Security: "Seguridad",
    Features: "Funciones",
    Shortcuts: "Atajos",
    Account: "Cuenta",
    Mail: "Correo",
    Calendar: "Calendario",
    Contacts: "Contactos",
    Files: "Archivos",
    Workspace: "Espacio de trabajo",
    "Privacy & Security": "Privacidad y seguridad",
    "Back to workspace": "Volver al espacio de trabajo",
    Language: "Idioma",
    Timezone: "Zona horaria",
    "Default app": "Aplicación predeterminada",
    "Display density": "Densidad de pantalla",
    "Used across the workspace interface.": "Se usa en toda la interfaz.",
    "Used for dates and times across mail and calendar.":
      "Se usa para fechas y horas del correo y calendario.",
    "The app you land in. Changing it switches you there now.":
      "La aplicación inicial. Cambiarla te lleva allí ahora.",
    "Overall spacing of the interface.": "Espaciado general de la interfaz.",
    "Automatic (device)": "Automático (dispositivo)",
    Comfortable: "Cómodo",
    Compact: "Compacto",
    Compose: "Redactar",
    Mailboxes: "Buzones",
    Starred: "Destacados",
    Important: "Importantes",
    Sent: "Enviados",
    Drafts: "Borradores",
    Archive: "Archivo",
    Junk: "Spam",
    Trash: "Papelera",
    Views: "Vistas",
    Month: "Mes",
    Week: "Semana",
    Day: "Día",
    Agenda: "Agenda",
    "Address books": "Libretas de direcciones",
    "Search mail": "Buscar correo",
    "Search results": "Resultados de búsqueda",
    "Search trash…": "Buscar en papelera…",
    "Search mail (try: from:X, has:attachment)":
      "Buscar correo (ej.: from:X, has:attachment)",
    "Language, timezone and workspace defaults":
      "Idioma, zona horaria y preferencias",
    "Theme, type, scale, and color vision": "Tema, tipografía, escala y color",
    "Reading pane, density and previews":
      "Panel de lectura, densidad y vistas previas",
    "Identity, signature and reply defaults": "Identidad, firma y respuestas",
    "Email and attachment file names": "Nombres de correos y adjuntos",
    "Addresses available for sending": "Direcciones disponibles para enviar",
    "Automatic out-of-office replies": "Respuestas automáticas de ausencia",
    "Incoming mail rules": "Reglas del correo entrante",
    "Reusable email drafts": "Borradores reutilizables",
    "Manage mailboxes": "Administrar buzones",
    "Organize mail with labels": "Organizar correo con etiquetas",
    "Images and trusted senders": "Imágenes y remitentes de confianza",
    "Connection and session safety": "Seguridad de conexión y sesión",
    "Turn optional capabilities on or off": "Activar o desactivar funciones",
    "Keyboard shortcut reference": "Atajos de teclado",
    "Profile and session": "Perfil y sesión",
    "Toggle sidebar": "Alternar barra lateral",
    "Choose mailbox": "Elegir buzón",
    "Advanced mail search": "Búsqueda avanzada",
    Back: "Volver",
  },
  fr: {
    Settings: "Paramètres",
    General: "Général",
    Appearance: "Apparence",
    Inbox: "Boîte de réception",
    Composing: "Rédaction",
    Downloads: "Téléchargements",
    Identities: "Identités",
    "Vacation responder": "Réponse automatique",
    Filters: "Filtres",
    Templates: "Modèles",
    Folders: "Dossiers",
    Tags: "Étiquettes",
    "Content & senders": "Contenu et expéditeurs",
    Security: "Sécurité",
    Features: "Fonctions",
    Shortcuts: "Raccourcis",
    Account: "Compte",
    Mail: "Courrier",
    Calendar: "Calendrier",
    Contacts: "Contacts",
    Files: "Fichiers",
    Workspace: "Espace de travail",
    "Privacy & Security": "Confidentialité et sécurité",
    "Back to workspace": "Retour à l'espace de travail",
    Language: "Langue",
    Timezone: "Fuseau horaire",
    "Default app": "Application par défaut",
    "Display density": "Densité d'affichage",
    "Used across the workspace interface.": "Utilisée dans toute l'interface.",
    "Used for dates and times across mail and calendar.":
      "Utilisé pour les dates du courrier et du calendrier.",
    "The app you land in. Changing it switches you there now.":
      "Application d'accueil. La modifier vous y mène immédiatement.",
    "Overall spacing of the interface.": "Espacement général de l'interface.",
    "Automatic (device)": "Automatique (appareil)",
    Comfortable: "Confortable",
    Compact: "Compact",
    Compose: "Rédiger",
    Mailboxes: "Boîtes aux lettres",
    Starred: "Favoris",
    Important: "Important",
    Sent: "Envoyés",
    Drafts: "Brouillons",
    Archive: "Archives",
    Junk: "Indésirables",
    Trash: "Corbeille",
    Views: "Vues",
    Month: "Mois",
    Week: "Semaine",
    Day: "Jour",
    Agenda: "Agenda",
    "Address books": "Carnets d'adresses",
    "Search mail": "Rechercher",
    "Search results": "Résultats de recherche",
    "Search trash…": "Chercher dans la corbeille…",
    "Search mail (try: from:X, has:attachment)":
      "Rechercher (ex. : from:X, has:attachment)",
    "Language, timezone and workspace defaults":
      "Langue, fuseau horaire et préférences",
    "Theme, type, scale, and color vision":
      "Thème, typographie, taille et couleurs",
    "Reading pane, density and previews":
      "Volet de lecture, densité et aperçus",
    "Identity, signature and reply defaults": "Identité, signature et réponses",
    "Email and attachment file names": "Noms des courriels et pièces jointes",
    "Addresses available for sending": "Adresses disponibles pour l'envoi",
    "Automatic out-of-office replies": "Réponses automatiques d'absence",
    "Incoming mail rules": "Règles du courrier entrant",
    "Reusable email drafts": "Brouillons réutilisables",
    "Manage mailboxes": "Gérer les boîtes aux lettres",
    "Organize mail with labels": "Organiser avec des étiquettes",
    "Images and trusted senders": "Images et expéditeurs fiables",
    "Connection and session safety": "Sécurité de connexion et de session",
    "Turn optional capabilities on or off":
      "Activer ou désactiver des fonctions",
    "Keyboard shortcut reference": "Raccourcis clavier",
    "Profile and session": "Profil et session",
    "Toggle sidebar": "Afficher la barre latérale",
    "Choose mailbox": "Choisir une boîte",
    "Advanced mail search": "Recherche avancée",
    Back: "Retour",
  },
  de: {
    Settings: "Einstellungen",
    General: "Allgemein",
    Appearance: "Darstellung",
    Inbox: "Posteingang",
    Composing: "Verfassen",
    Downloads: "Downloads",
    Identities: "Identitäten",
    "Vacation responder": "Abwesenheitsnotiz",
    Filters: "Filter",
    Templates: "Vorlagen",
    Folders: "Ordner",
    Tags: "Schlagwörter",
    "Content & senders": "Inhalte und Absender",
    Security: "Sicherheit",
    Features: "Funktionen",
    Shortcuts: "Kurzbefehle",
    Account: "Konto",
    Mail: "E-Mail",
    Calendar: "Kalender",
    Contacts: "Kontakte",
    Files: "Dateien",
    Workspace: "Arbeitsbereich",
    "Privacy & Security": "Datenschutz und Sicherheit",
    "Back to workspace": "Zurück zum Arbeitsbereich",
    Language: "Sprache",
    Timezone: "Zeitzone",
    "Default app": "Standard-App",
    "Display density": "Anzeigedichte",
    "Used across the workspace interface.": "Gilt für die gesamte Oberfläche.",
    "Used for dates and times across mail and calendar.":
      "Gilt für Datum und Uhrzeit in Mail und Kalender.",
    "The app you land in. Changing it switches you there now.":
      "Start-App. Eine Änderung wechselt sofort dorthin.",
    "Overall spacing of the interface.": "Abstände der Oberfläche.",
    "Automatic (device)": "Automatisch (Gerät)",
    Comfortable: "Bequem",
    Compact: "Kompakt",
    Compose: "Verfassen",
    Mailboxes: "Postfächer",
    Starred: "Markiert",
    Important: "Wichtig",
    Sent: "Gesendet",
    Drafts: "Entwürfe",
    Archive: "Archiv",
    Junk: "Spam",
    Trash: "Papierkorb",
    Views: "Ansichten",
    Month: "Monat",
    Week: "Woche",
    Day: "Tag",
    Agenda: "Agenda",
    "Address books": "Adressbücher",
    "Search mail": "E-Mails suchen",
    "Search results": "Suchergebnisse",
    "Search trash…": "Papierkorb durchsuchen…",
    "Search mail (try: from:X, has:attachment)":
      "E-Mails suchen (z. B. from:X, has:attachment)",
    "Language, timezone and workspace defaults":
      "Sprache, Zeitzone und Voreinstellungen",
    "Theme, type, scale, and color vision": "Design, Schrift, Größe und Farben",
    "Reading pane, density and previews": "Lesebereich, Dichte und Vorschauen",
    "Identity, signature and reply defaults":
      "Identität, Signatur und Antworten",
    "Email and attachment file names": "Namen für E-Mails und Anhänge",
    "Addresses available for sending": "Verfügbare Absenderadressen",
    "Automatic out-of-office replies": "Automatische Abwesenheitsantworten",
    "Incoming mail rules": "Regeln für eingehende E-Mails",
    "Reusable email drafts": "Wiederverwendbare Entwürfe",
    "Manage mailboxes": "Postfächer verwalten",
    "Organize mail with labels": "E-Mails mit Schlagwörtern ordnen",
    "Images and trusted senders": "Bilder und vertrauenswürdige Absender",
    "Connection and session safety": "Verbindungs- und Sitzungsschutz",
    "Turn optional capabilities on or off":
      "Optionale Funktionen ein- oder ausschalten",
    "Keyboard shortcut reference": "Tastenkombinationen",
    "Profile and session": "Profil und Sitzung",
    "Toggle sidebar": "Seitenleiste umschalten",
    "Choose mailbox": "Postfach wählen",
    "Advanced mail search": "Erweiterte Suche",
    Back: "Zurück",
  },
  ar: {
    Settings: "الإعدادات",
    General: "عام",
    Appearance: "المظهر",
    Inbox: "الوارد",
    Composing: "الإنشاء",
    Downloads: "التنزيلات",
    Identities: "الهويات",
    "Vacation responder": "الرد التلقائي",
    Filters: "عوامل التصفية",
    Templates: "القوالب",
    Folders: "المجلدات",
    Tags: "الوسوم",
    "Content & senders": "المحتوى والمرسلون",
    Security: "الأمان",
    Features: "الميزات",
    Shortcuts: "الاختصارات",
    Account: "الحساب",
    Mail: "البريد",
    Calendar: "التقويم",
    Contacts: "جهات الاتصال",
    Files: "الملفات",
    Workspace: "مساحة العمل",
    "Privacy & Security": "الخصوصية والأمان",
    "Back to workspace": "العودة إلى مساحة العمل",
    Language: "اللغة",
    Timezone: "المنطقة الزمنية",
    "Default app": "التطبيق الافتراضي",
    "Display density": "كثافة العرض",
    "Used across the workspace interface.": "تُستخدم في واجهة مساحة العمل.",
    "Used for dates and times across mail and calendar.":
      "تُستخدم للتواريخ والأوقات في البريد والتقويم.",
    "The app you land in. Changing it switches you there now.":
      "التطبيق الذي يُفتح أولًا. تغييره ينقلك إليه الآن.",
    "Overall spacing of the interface.": "تباعد عناصر الواجهة.",
    "Automatic (device)": "تلقائي (الجهاز)",
    Comfortable: "مريح",
    Compact: "مضغوط",
    Compose: "إنشاء",
    Mailboxes: "صناديق البريد",
    Starred: "المميزة",
    Important: "المهمة",
    Sent: "المرسلة",
    Drafts: "المسودات",
    Archive: "الأرشيف",
    Junk: "غير المرغوب فيه",
    Trash: "المهملات",
    Views: "العروض",
    Month: "الشهر",
    Week: "الأسبوع",
    Day: "اليوم",
    Agenda: "جدول الأعمال",
    "Address books": "دفاتر العناوين",
    "Search mail": "البحث في البريد",
    "Search results": "نتائج البحث",
    "Search trash…": "البحث في المهملات…",
    "Search mail (try: from:X, has:attachment)":
      "البحث في البريد (مثل: from:X, has:attachment)",
    "Language, timezone and workspace defaults":
      "اللغة والمنطقة الزمنية وتفضيلات مساحة العمل",
    "Theme, type, scale, and color vision": "السمة والخط والحجم والألوان",
    "Reading pane, density and previews": "جزء القراءة والكثافة والمعاينات",
    "Identity, signature and reply defaults": "الهوية والتوقيع وإعدادات الرد",
    "Email and attachment file names": "أسماء ملفات الرسائل والمرفقات",
    "Addresses available for sending": "العناوين المتاحة للإرسال",
    "Automatic out-of-office replies": "ردود الغياب التلقائية",
    "Incoming mail rules": "قواعد البريد الوارد",
    "Reusable email drafts": "مسودات قابلة لإعادة الاستخدام",
    "Manage mailboxes": "إدارة صناديق البريد",
    "Organize mail with labels": "تنظيم البريد بالوسوم",
    "Images and trusted senders": "الصور والمرسلون الموثوقون",
    "Connection and session safety": "أمان الاتصال والجلسة",
    "Turn optional capabilities on or off":
      "تشغيل الميزات الاختيارية أو إيقافها",
    "Keyboard shortcut reference": "مرجع اختصارات لوحة المفاتيح",
    "Profile and session": "الملف الشخصي والجلسة",
    "Toggle sidebar": "تبديل الشريط الجانبي",
    "Choose mailbox": "اختيار صندوق بريد",
    "Advanced mail search": "بحث متقدم في البريد",
    Back: "رجوع",
    "New folder": "مجلد جديد",
    "Folder name": "اسم المجلد",
    "New folder name": "اسم المجلد الجديد",
    "Select a conversation to read it.": "اختر محادثة لقراءتها.",
    "No messages matched your search.": "لم تطابق أي رسالة بحثك.",
    "This mailbox is empty.": "صندوق البريد هذا فارغ.",
    "Load more messages": "تحميل مزيد من الرسائل",
    "Loading more messages…": "جارٍ تحميل المزيد…",
  },
} satisfies Record<Language, Partial<Record<Key, string>>>

export function normalizeLanguage(value: string | undefined): Language {
  return LANGUAGES.find((item) => item.value === value)?.value ?? "en"
}

export function languageDirection(language: Language): "ltr" | "rtl" {
  return LANGUAGES.find((item) => item.value === language)?.dir ?? "ltr"
}

export function translate(language: Language, key: Key): string {
  const selected: Partial<Record<Key, string>> = translations[language]
  return selected[key] ?? english[key]
}

export function useLanguage() {
  const { data } = usePreferences()
  const language = normalizeLanguage(data?.language)
  return {
    language,
    t: (key: Key) => translate(language, key),
    direction: languageDirection(language),
  }
}

export function LanguageSync() {
  const { language, direction } = useLanguage()
  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dir = direction
  }, [language, direction])
  return null
}
