/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DesignSystemRouteRouteImport } from './routes/design-system/route'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductRouteImport } from './routes/product'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DesignSystemIndexRouteImport } from './routes/design-system/index'
import { Route as DesignSystemAccentsRouteImport } from './routes/design-system/accents'
import { Route as DesignSystemAuthRouteImport } from './routes/design-system/auth'
import { Route as DesignSystemCalendarRouteImport } from './routes/design-system/calendar'
import { Route as DesignSystemColorsRouteImport } from './routes/design-system/colors'
import { Route as DesignSystemContactsRouteImport } from './routes/design-system/contacts'
import { Route as DesignSystemFilesRouteImport } from './routes/design-system/files'
import { Route as DesignSystemMailRouteImport } from './routes/design-system/mail'
import { Route as DesignSystemShellRouteImport } from './routes/design-system/shell'
import { Route as DesignSystemThemeRouteImport } from './routes/design-system/theme'
import { Route as DesignSystemTypographyRouteImport } from './routes/design-system/typography'
import { Route as DesignSystemComponentsSlugRouteImport } from './routes/design-system/components.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRouteRoute = DesignSystemRouteRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIndexRoute = DesignSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemAccentsRoute = DesignSystemAccentsRouteImport.update({
  id: '/accents',
  path: '/accents',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemAuthRoute = DesignSystemAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemCalendarRoute = DesignSystemCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemColorsRoute = DesignSystemColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemContactsRoute = DesignSystemContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemFilesRoute = DesignSystemFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemMailRoute = DesignSystemMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemShellRoute = DesignSystemShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemThemeRoute = DesignSystemThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemTypographyRoute = DesignSystemTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemComponentsSlugRoute =
  DesignSystemComponentsSlugRouteImport.update({
    id: '/components/$slug',
    path: '/components/$slug',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/request-access': typeof RequestAccessRoute
  '/settings': typeof SettingsRoute
  '/design-system/accents': typeof DesignSystemAccentsRoute
  '/design-system/auth': typeof DesignSystemAuthRoute
  '/design-system/calendar': typeof DesignSystemCalendarRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/contacts': typeof DesignSystemContactsRoute
  '/design-system/files': typeof DesignSystemFilesRoute
  '/design-system/mail': typeof DesignSystemMailRoute
  '/design-system/shell': typeof DesignSystemShellRoute
  '/design-system/theme': typeof DesignSystemThemeRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/design-system/components/$slug': typeof DesignSystemComponentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/request-access': typeof RequestAccessRoute
  '/settings': typeof SettingsRoute
  '/design-system/accents': typeof DesignSystemAccentsRoute
  '/design-system/auth': typeof DesignSystemAuthRoute
  '/design-system/calendar': typeof DesignSystemCalendarRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/contacts': typeof DesignSystemContactsRoute
  '/design-system/files': typeof DesignSystemFilesRoute
  '/design-system/mail': typeof DesignSystemMailRoute
  '/design-system/shell': typeof DesignSystemShellRoute
  '/design-system/theme': typeof DesignSystemThemeRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/design-system': typeof DesignSystemIndexRoute
  '/design-system/components/$slug': typeof DesignSystemComponentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/request-access': typeof RequestAccessRoute
  '/settings': typeof SettingsRoute
  '/design-system/accents': typeof DesignSystemAccentsRoute
  '/design-system/auth': typeof DesignSystemAuthRoute
  '/design-system/calendar': typeof DesignSystemCalendarRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/contacts': typeof DesignSystemContactsRoute
  '/design-system/files': typeof DesignSystemFilesRoute
  '/design-system/mail': typeof DesignSystemMailRoute
  '/design-system/shell': typeof DesignSystemShellRoute
  '/design-system/theme': typeof DesignSystemThemeRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/design-system/components/$slug': typeof DesignSystemComponentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/app'
    | '/demo'
    | '/enterprise'
    | '/login'
    | '/product'
    | '/request-access'
    | '/settings'
    | '/design-system/accents'
    | '/design-system/auth'
    | '/design-system/calendar'
    | '/design-system/colors'
    | '/design-system/contacts'
    | '/design-system/files'
    | '/design-system/mail'
    | '/design-system/shell'
    | '/design-system/theme'
    | '/design-system/typography'
    | '/design-system/'
    | '/design-system/components/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/enterprise'
    | '/login'
    | '/product'
    | '/request-access'
    | '/settings'
    | '/design-system/accents'
    | '/design-system/auth'
    | '/design-system/calendar'
    | '/design-system/colors'
    | '/design-system/contacts'
    | '/design-system/files'
    | '/design-system/mail'
    | '/design-system/shell'
    | '/design-system/theme'
    | '/design-system/typography'
    | '/design-system'
    | '/design-system/components/$slug'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/app'
    | '/demo'
    | '/enterprise'
    | '/login'
    | '/product'
    | '/request-access'
    | '/settings'
    | '/design-system/accents'
    | '/design-system/auth'
    | '/design-system/calendar'
    | '/design-system/colors'
    | '/design-system/contacts'
    | '/design-system/files'
    | '/design-system/mail'
    | '/design-system/shell'
    | '/design-system/theme'
    | '/design-system/typography'
    | '/design-system/'
    | '/design-system/components/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRouteRoute: typeof DesignSystemRouteRouteWithChildren
  AppRoute: typeof AppRoute
  DemoRoute: typeof DemoRoute
  EnterpriseRoute: typeof EnterpriseRoute
  LoginRoute: typeof LoginRoute
  ProductRoute: typeof ProductRoute
  RequestAccessRoute: typeof RequestAccessRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/': {
      id: '/design-system/'
      path: '/'
      fullPath: '/design-system/'
      preLoaderRoute: typeof DesignSystemIndexRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/accents': {
      id: '/design-system/accents'
      path: '/accents'
      fullPath: '/design-system/accents'
      preLoaderRoute: typeof DesignSystemAccentsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/auth': {
      id: '/design-system/auth'
      path: '/auth'
      fullPath: '/design-system/auth'
      preLoaderRoute: typeof DesignSystemAuthRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/calendar': {
      id: '/design-system/calendar'
      path: '/calendar'
      fullPath: '/design-system/calendar'
      preLoaderRoute: typeof DesignSystemCalendarRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/colors': {
      id: '/design-system/colors'
      path: '/colors'
      fullPath: '/design-system/colors'
      preLoaderRoute: typeof DesignSystemColorsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/contacts': {
      id: '/design-system/contacts'
      path: '/contacts'
      fullPath: '/design-system/contacts'
      preLoaderRoute: typeof DesignSystemContactsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/files': {
      id: '/design-system/files'
      path: '/files'
      fullPath: '/design-system/files'
      preLoaderRoute: typeof DesignSystemFilesRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/mail': {
      id: '/design-system/mail'
      path: '/mail'
      fullPath: '/design-system/mail'
      preLoaderRoute: typeof DesignSystemMailRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/shell': {
      id: '/design-system/shell'
      path: '/shell'
      fullPath: '/design-system/shell'
      preLoaderRoute: typeof DesignSystemShellRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/theme': {
      id: '/design-system/theme'
      path: '/theme'
      fullPath: '/design-system/theme'
      preLoaderRoute: typeof DesignSystemThemeRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/typography': {
      id: '/design-system/typography'
      path: '/typography'
      fullPath: '/design-system/typography'
      preLoaderRoute: typeof DesignSystemTypographyRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/$slug': {
      id: '/design-system/components/$slug'
      path: '/components/$slug'
      fullPath: '/design-system/components/$slug'
      preLoaderRoute: typeof DesignSystemComponentsSlugRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
  }
}

interface DesignSystemRouteRouteChildren {
  DesignSystemAccentsRoute: typeof DesignSystemAccentsRoute
  DesignSystemAuthRoute: typeof DesignSystemAuthRoute
  DesignSystemCalendarRoute: typeof DesignSystemCalendarRoute
  DesignSystemColorsRoute: typeof DesignSystemColorsRoute
  DesignSystemContactsRoute: typeof DesignSystemContactsRoute
  DesignSystemFilesRoute: typeof DesignSystemFilesRoute
  DesignSystemMailRoute: typeof DesignSystemMailRoute
  DesignSystemShellRoute: typeof DesignSystemShellRoute
  DesignSystemThemeRoute: typeof DesignSystemThemeRoute
  DesignSystemTypographyRoute: typeof DesignSystemTypographyRoute
  DesignSystemIndexRoute: typeof DesignSystemIndexRoute
  DesignSystemComponentsSlugRoute: typeof DesignSystemComponentsSlugRoute
}

const DesignSystemRouteRouteChildren: DesignSystemRouteRouteChildren = {
  DesignSystemAccentsRoute: DesignSystemAccentsRoute,
  DesignSystemAuthRoute: DesignSystemAuthRoute,
  DesignSystemCalendarRoute: DesignSystemCalendarRoute,
  DesignSystemColorsRoute: DesignSystemColorsRoute,
  DesignSystemContactsRoute: DesignSystemContactsRoute,
  DesignSystemFilesRoute: DesignSystemFilesRoute,
  DesignSystemMailRoute: DesignSystemMailRoute,
  DesignSystemShellRoute: DesignSystemShellRoute,
  DesignSystemThemeRoute: DesignSystemThemeRoute,
  DesignSystemTypographyRoute: DesignSystemTypographyRoute,
  DesignSystemIndexRoute: DesignSystemIndexRoute,
  DesignSystemComponentsSlugRoute: DesignSystemComponentsSlugRoute,
}

const DesignSystemRouteRouteWithChildren =
  DesignSystemRouteRoute._addFileChildren(DesignSystemRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRouteRoute: DesignSystemRouteRouteWithChildren,
  AppRoute: AppRoute,
  DemoRoute: DemoRoute,
  EnterpriseRoute: EnterpriseRoute,
  LoginRoute: LoginRoute,
  ProductRoute: ProductRoute,
  RequestAccessRoute: RequestAccessRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
